CREATE SCHEMA IF NOT EXISTS thaiflux_app;

CREATE TABLE IF NOT EXISTS thaiflux_app.users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);
